# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-27 10:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20191022_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
    ]
