# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-14 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_commentdislike_commentlike_postdislike_postlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentdislike',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='commentdislike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='postdislike',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postdislike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='user_id',
            new_name='user',
        ),
    ]
